version: "3.5"

services:

  caddy:
    image: "lucaslorentz/caddy-docker-proxy:ci-alpine"
    ports:
      - "${HTTP}:80"
      - "${HTTPS}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/caddy/:/data
    restart: unless-stopped
    environment:
      - CADDY_INGRESS_NETWORKS=up_proxy_network
    labels:
      caddy: ${LISTEN_DOMAIN}
      caddy.@upgrade.0_header: Upgrade-Insecure-Requests 1
      caddy.@upgrade.1_protocol: http
      caddy.redir: "@upgrade https://{host}{uri} 308"
  proxy:
    image: "unifiedpush/common-proxies:testing"
    labels:
      caddy: ${LISTEN_DOMAIN}
      caddy.@match.path: /UP* /FCM* /_matrix*
      caddy.reverse_proxy: "@match {{upstreams 5000}}"
    restart: unless-stopped
    environment:
      - UP_REWRITE_GOTIFY_ENABLE=true
      - UP_REWRITE_GOTIFY_ADDRESS=gotify
      - UP_REWRITE_GOTIFY_SCHEME=http
      - UP_GATEWAY_MATRIX_ENABLE=true
  gotify:
    image: gotify/server
    volumes:
      - "./data/gotify:/app/data"
    labels:
      caddy: ${LISTEN_DOMAIN}
      caddy.reverse_proxy: "* {{upstreams 80}}"
    restart: unless-stopped
networks:
  default:
    name: up_proxy_network
